steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/ferrous-arch-90702/cloudrun-helloworld", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/ferrous-arch-90702/cloudrun-helloworld"]
    # Deploy an image from Container Registry to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "cloudrun-helloworld",
        "--image",
        "gcr.io/ferrous-arch-90702/cloudrun-helloworld",
        "--region",
        "asia-northeast1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
